name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"      # 每天 UTC 0 点自动运行一次
  workflow_dispatch:        # 也可手动触发

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出你的仓库代码（必须）
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 运行 snk 生成贡献图贪吃蛇 SVG
      - name: Generate snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: L-w-p-999
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. 列出当前目录，帮助调试（可选）
      - name: List files
        run: ls -R .

      # 4. 部署到 output 分支
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # 确保和你的 Pages 设置一致
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
